spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DeepLink
    username: user
    password: user_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
server:
  port: 8081

params:
  deeplinks:
    boutiqueId: 'CampaignId'
    merchantId: 'MerchantId'
    productId: 'ContentId'
    page: 'Page'

  weblinks:
    CampaignId: 'boutiqueId'
    MerchantId: 'merchantId'
